
#define COMP_PWR_REL_DDR DDRB
#define COMP_PWR_BTN_DDR DDRB
#define COMP_PWR_REL_PIN PB7
#define COMP_PWR_BTN_PIN PB6
#define COMP_PWR_REL_PORT PORTB
#define COMP_PWR_BTN_PORT PORTB

#define LAMP_RED_PORT PORTH
#define LAMP_RED_DDR DDRH
#define LAMP_RED_PIN PH6

#define LAMP_WHT_PORT PORTH
#define LAMP_WHT_DDR DDRH
#define LAMP_WHT_PIN PH6